// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDpYHADAp_OQ_mG1v1WSrlgsfSHZoGSQM',
    appId: '1:188645605684:web:e45cde80efe7448cc6e561',
    messagingSenderId: '188645605684',
    projectId: 'daily-habit-app-5b315',
    authDomain: 'daily-habit-app-5b315.firebaseapp.com',
    storageBucket: 'daily-habit-app-5b315.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjgnotPMYZAcOq3h3O4pJAhPLZAPGpAII',
    appId: '1:188645605684:android:f9d74674832bfeb6c6e561',
    messagingSenderId: '188645605684',
    projectId: 'daily-habit-app-5b315',
    storageBucket: 'daily-habit-app-5b315.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGrSdw1j51AjoxuG3a12AKVXH4i8XnE7c',
    appId: '1:188645605684:ios:849b56db864275c0c6e561',
    messagingSenderId: '188645605684',
    projectId: 'daily-habit-app-5b315',
    storageBucket: 'daily-habit-app-5b315.firebasestorage.app',
    iosBundleId: 'com.example.dailyHabitApp',
  );
}
